#!/usr/bin/env bash


# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

# Update package list and install Nginx if not installed
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx HTTP through the firewall
sudo ufw allow 'Nginx HTTP'

# Create necessary directories and set permissions
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www

# Create default index and 404 pages
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Create Nginx server configuration with custom header and other settings
server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://youtube.com permanent;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}"

# Write the server configuration to the default Nginx site config
echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
