#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
#sudo sed -i 's/server_name _;.*/server_name _;\n\tadd_header X-Served-By \$hostname;/' /etc/nginx/sites-enabled/default 


# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

# Update package list and install Nginx if not installed
apt-get update
apt-get install -y nginx

# Get the hostname
HOSTNAME=$(hostname)

# Create a backup of the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add the custom header to the Nginx configuration
sed -i "/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
systemctl restart nginx
